#!/bin/bash

# Internal Management System API Test Commands
# Copy these commands to test the APIs

echo "=== INTERNAL MANAGEMENT SYSTEM API TEST ==="
echo ""

# 1. Register Admin User
echo "1. Register Admin User:"
echo "curl -X POST http://localhost:8080/api/auth/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"username\": \"admin\","
echo "    \"email\": \"admin@company.com\","
echo "    \"password\": \"admin123\","
echo "    \"role\": \"ADMIN\""
echo "  }'"
echo ""

# 2. Register HR User
echo "2. Register HR User:"
echo "curl -X POST http://localhost:8080/api/auth/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"username\": \"hr_manager\","
echo "    \"email\": \"hr@company.com\","
echo "    \"password\": \"hr123\","
echo "    \"role\": \"HR\""
echo "  }'"
echo ""

# 3. Register Warehouse User
echo "3. Register Warehouse User:"
echo "curl -X POST http://localhost:8080/api/auth/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"username\": \"warehouse_mgr\","
echo "    \"email\": \"warehouse@company.com\","
echo "    \"password\": \"wh123\","
echo "    \"role\": \"WAREHOUSE\""
echo "  }'"
echo ""

# 4. Login as Admin (store token for later use)
echo "4. Login as Admin:"
echo "curl -X POST http://localhost:8080/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"username\": \"admin\","
echo "    \"password\": \"admin123\""
echo "  }'"
echo ""

# 5. Create Department
echo "5. Create Department:"
echo "curl -X POST http://localhost:8080/api/departments \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE' \\"
echo "  -d '{"
echo "    \"name\": \"Information Technology\","
echo "    \"description\": \"IT Department responsible for technology infrastructure\","
echo "    \"managerId\": null"
echo "  }'"
echo ""

# 6. Create Position
echo "6. Create Position:"
echo "curl -X POST http://localhost:8080/api/positions \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE' \\"
echo "  -d '{"
echo "    \"title\": \"Senior Java Developer\","
echo "    \"description\": \"Senior developer with 5+ years experience\","
echo "    \"baseSalary\": 15000000,"
echo "    \"departmentId\": 1"
echo "  }'"
echo ""

# 7. Create Employee
echo "7. Create Employee:"
echo "curl -X POST http://localhost:8080/api/employees \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE' \\"
echo "  -d '{"
echo "    \"employeeCode\": \"EMP001\","
echo "    \"firstName\": \"Nguyen\","
echo "    \"lastName\": \"Van A\","
echo "    \"email\": \"nguyenvana@company.com\","
echo "    \"phone\": \"0123456789\","
echo "    \"dateOfBirth\": \"1990-01-01\","
echo "    \"address\": \"123 Main Street, Hanoi\","
echo "    \"hireDate\": \"2023-01-01\","
echo "    \"departmentId\": 1,"
echo "    \"positionId\": 1,"
echo "    \"salary\": 12000000"
echo "  }'"
echo ""

# 8. Create Category
echo "8. Create Product Category:"
echo "curl -X POST http://localhost:8080/api/categories \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE' \\"
echo "  -d '{"
echo "    \"name\": \"Electronics\","
echo "    \"description\": \"Electronic devices and components\","
echo "    \"parentCategoryId\": null"
echo "  }'"
echo ""

# 9. Create Product
echo "9. Create Product:"
echo "curl -X POST http://localhost:8080/api/products \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE' \\"
echo "  -d '{"
echo "    \"productCode\": \"LAP001\","
echo "    \"name\": \"Gaming Laptop\","
echo "    \"description\": \"High-performance gaming laptop\","
echo "    \"categoryId\": 1,"
echo "    \"unitPrice\": 25000000,"
echo "    \"unitOfMeasure\": \"piece\","
echo "    \"minStockLevel\": 5,"
echo "    \"maxStockLevel\": 100,"
echo "    \"barcode\": \"1234567890123\","
echo "    \"supplier\": \"Tech Supplier Inc\""
echo "  }'"
echo ""

# 10. Create Warehouse
echo "10. Create Warehouse:"
echo "curl -X POST http://localhost:8080/api/warehouses \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE' \\"
echo "  -d '{"
echo "    \"warehouseCode\": \"WH001\","
echo "    \"name\": \"Main Warehouse\","
echo "    \"description\": \"Primary storage facility\","
echo "    \"address\": \"456 Industrial Zone, Hanoi\","
echo "    \"phone\": \"0987654321\","
echo "    \"managerName\": \"Tran Van B\","
echo "    \"capacity\": 10000,"
echo "    \"unitOfMeasure\": \"square_meters\""
echo "  }'"
echo ""

# 11. Create Inventory
echo "11. Create Inventory Record:"
echo "curl -X POST http://localhost:8080/api/inventories \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE' \\"
echo "  -d '{"
echo "    \"productId\": 1,"
echo "    \"warehouseId\": 1,"
echo "    \"currentQuantity\": 50,"
echo "    \"reservedQuantity\": 5,"
echo "    \"minQuantity\": 10,"
echo "    \"maxQuantity\": 200,"
echo "    \"unitCost\": 20000000,"
echo "    \"locationCode\": \"A-01-01\""
echo "  }'"
echo ""

# 12. Create Stock Import
echo "12. Create Stock Import:"
echo "curl -X POST http://localhost:8080/api/stock-imports \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE' \\"
echo "  -d '{"
echo "    \"importCode\": \"IMP001\","
echo "    \"warehouseId\": 1,"
echo "    \"supplierName\": \"Tech Supplier Inc\","
echo "    \"supplierInvoice\": \"INV-2025-001\","
echo "    \"importDate\": \"2025-12-03\","
echo "    \"totalQuantity\": 25,"
echo "    \"totalAmount\": 500000000,"
echo "    \"status\": \"APPROVED\","
echo "    \"notes\": \"New laptop shipment\","
echo "    \"createdBy\": \"warehouse_mgr\","
echo "    \"approvedBy\": \"admin\""
echo "  }'"
echo ""

# 13. Get All Departments
echo "13. Get All Departments:"
echo "curl -X GET http://localhost:8080/api/departments \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE'"
echo ""

# 14. Get All Employees
echo "14. Get All Employees:"
echo "curl -X GET http://localhost:8080/api/employees \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE'"
echo ""

# 15. Get Employee by ID
echo "15. Get Employee by ID:"
echo "curl -X GET http://localhost:8080/api/employees/1 \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE'"
echo ""

# 16. Update Employee
echo "16. Update Employee:"
echo "curl -X PUT http://localhost:8080/api/employees/1 \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE' \\"
echo "  -d '{"
echo "    \"employeeCode\": \"EMP001\","
echo "    \"firstName\": \"Nguyen\","
echo "    \"lastName\": \"Van A\","
echo "    \"email\": \"nguyenvana@company.com\","
echo "    \"phone\": \"0123456789\","
echo "    \"dateOfBirth\": \"1990-01-01\","
echo "    \"address\": \"123 Main Street, Hanoi\","
echo "    \"hireDate\": \"2023-01-01\","
echo "    \"departmentId\": 1,"
echo "    \"positionId\": 1,"
echo "    \"salary\": 15000000"
echo "  }'"
echo ""

# 17. Delete Employee
echo "17. Delete Employee:"
echo "curl -X DELETE http://localhost:8080/api/employees/1 \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN_HERE'"
echo ""

echo "=== POSTMAN IMPORT FORMAT ==="
echo ""

# Postman Collection JSON format
echo "Copy the following JSON to import into Postman:"
echo "{"
echo "  \"info\": {"
echo "    \"name\": \"Internal Management System API\","
echo "    \"schema\": \"https://schema.getpostman.com/json/collection/v2.1.0/collection.json\""
echo "  },"
echo "  \"item\": ["
echo "    {"
echo "      \"name\": \"Auth\","
echo "      \"item\": ["
echo "        {"
echo "          \"name\": \"Register\","
echo "          \"request\": {"
echo "            \"method\": \"POST\","
echo "            \"header\": ["
echo "              {"
echo "                \"key\": \"Content-Type\","
echo "                \"value\": \"application/json\""
echo "              }"
echo "            ],"
echo "            \"body\": {"
echo "              \"mode\": \"raw\","
echo "              \"raw\": \"{\\\"username\\\":\\\"admin\\\",\\\"email\\\":\\\"admin@company.com\\\",\\\"password\\\":\\\"admin123\\\",\\\"role\\\":\\\"ADMIN\\\"}\""
echo "            },"
echo "            \"url\": {"
echo "              \"raw\": \"http://localhost:8080/api/auth/register\","
echo "              \"protocol\": \"http\","
echo "              \"host\": [\"localhost\"],"
echo "              \"port\": \"8080\","
echo "              \"path\": [\"api\", \"auth\", \"register\"]"
echo "            }"
echo "          }"
echo "        },"
echo "        {"
echo "          \"name\": \"Login\","
echo "          \"request\": {"
echo "            \"method\": \"POST\","
echo "            \"header\": ["
echo "              {"
echo "                \"key\": \"Content-Type\","
echo "                \"value\": \"application/json\""
echo "              }"
echo "            ],"
echo "            \"body\": {"
echo "              \"mode\": \"raw\","
echo "              \"raw\": \"{\\\"username\\\":\\\"admin\\\",\\\"password\\\":\\\"admin123\\\"}\""
echo "            },"
echo "            \"url\": {"
echo "              \"raw\": \"http://localhost:8080/api/auth/login\","
echo "              \"protocol\": \"http\","
echo "              \"host\": [\"localhost\"],"
echo "              \"port\": \"8080\","
echo "              \"path\": [\"api\", \"auth\", \"login\"]"
echo "            }"
echo "          }"
echo "        }"
echo "      ]"
echo "    },"
echo "    {"
echo "      \"name\": \"HRM\","
echo "      \"item\": ["
echo "        {"
echo "          \"name\": \"Create Department\","
echo "          \"request\": {"
echo "            \"method\": \"POST\","
echo "            \"header\": ["
echo "              {"
echo "                \"key\": \"Content-Type\","
echo "                \"value\": \"application/json\""
echo "              },"
echo "              {"
echo "                \"key\": \"Authorization\","
echo "                \"value\": \"Bearer YOUR_JWT_TOKEN_HERE\""
echo "              }"
echo "            ],"
echo "            \"body\": {"
echo "              \"mode\": \"raw\","
echo "              \"raw\": \"{\\\"name\\\":\\\"Information Technology\\\",\\\"description\\\":\\\"IT Department responsible for technology infrastructure\\\",\\\"managerId\\\":null}\""
echo "            },"
echo "            \"url\": {"
echo "              \"raw\": \"http://localhost:8080/api/departments\","
echo "              \"protocol\": \"http\","
echo "              \"host\": [\"localhost\"],"
echo "              \"port\": \"8080\","
echo "              \"path\": [\"api\", \"departments\"]"
echo "            }"
echo "          }"
echo "        },"
echo "        {"
echo "          \"name\": \"Create Employee\","
echo "          \"request\": {"
echo "            \"method\": \"POST\","
echo "            \"header\": ["
echo "              {"
echo "                \"key\": \"Content-Type\","
echo "                \"value\": \"application/json\""
echo "              },"
echo "              {"
echo "                \"key\": \"Authorization\","
echo "                \"value\": \"Bearer YOUR_JWT_TOKEN_HERE\""
echo "              }"
echo "            ],"
echo "            \"body\": {"
echo "              \"mode\": \"raw\","
echo "              \"raw\": \"{\\\"employeeCode\\\":\\\"EMP001\\\",\\\"firstName\\\":\\\"Nguyen\\\",\\\"lastName\\\":\\\"Van A\\\",\\\"email\\\":\\\"nguyenvana@company.com\\\",\\\"phone\\\":\\\"0123456789\\\",\\\"dateOfBirth\\\":\\\"1990-01-01\\\",\\\"address\\\":\\\"123 Main Street, Hanoi\\\",\\\"hireDate\\\":\\\"2023-01-01\\\",\\\"departmentId\\\":1,\\\"positionId\\\":1,\\\"salary\\\":12000000}\""
echo "            },"
echo "            \"url\": {"
echo "              \"raw\": \"http://localhost:8080/api/employees\","
echo "              \"protocol\": \"http\","
echo "              \"host\": [\"localhost\"],"
echo "              \"port\": \"8080\","
echo "              \"path\": [\"api\", \"employees\"]"
echo "            }"
echo "          }"
echo "        }"
echo "      ]"
echo "    },"
echo "    {"
echo "      \"name\": \"Warehouse\","
echo "      \"item\": ["
echo "        {"
echo "          \"name\": \"Create Category\","
echo "          \"request\": {"
echo "            \"method\": \"POST\","
echo "            \"header\": ["
echo "              {"
echo "                \"key\": \"Content-Type\","
echo "                \"value\": \"application/json\""
echo "              },"
echo "              {"
echo "                \"key\": \"Authorization\","
echo "                \"value\": \"Bearer YOUR_JWT_TOKEN_HERE\""
echo "              }"
echo "            ],"
echo "            \"body\": {"
echo "              \"mode\": \"raw\","
echo "              \"raw\": \"{\\\"name\\\":\\\"Electronics\\\",\\\"description\\\":\\\"Electronic devices and components\\\",\\\"parentCategoryId\\\":null}\""
echo "            },"
echo "            \"url\": {"
echo "              \"raw\": \"http://localhost:8080/api/categories\","
echo "              \"protocol\": \"http\","
echo "              \"host\": [\"localhost\"],"
echo "              \"port\": \"8080\","
echo "              \"path\": [\"api\", \"categories\"]"
echo "            }"
echo "          }"
echo "        },"
echo "        {"
echo "          \"name\": \"Create Product\","
echo "          \"request\": {"
echo "            \"method\": \"POST\","
echo "            \"header\": ["
echo "              {"
echo "                \"key\": \"Content-Type\","
echo "                \"value\": \"application/json\""
echo "              },"
echo "              {"
echo "                \"key\": \"Authorization\","
echo "                \"value\": \"Bearer YOUR_JWT_TOKEN_HERE\""
echo "              }"
echo "            ],"
echo "            \"body\": {"
echo "              \"mode\": \"raw\","
echo "              \"raw\": \"{\\\"productCode\\\":\\\"LAP001\\\",\\\"name\\\":\\\"Gaming Laptop\\\",\\\"description\\\":\\\"High-performance gaming laptop\\\",\\\"categoryId\\\":1,\\\"unitPrice\\\":25000000,\\\"unitOfMeasure\\\":\\\"piece\\\",\\\"minStockLevel\\\":5,\\\"maxStockLevel\\\":100,\\\"barcode\\\":\\\"1234567890123\\\",\\\"supplier\\\":\\\"Tech Supplier Inc\\\"}\""
echo "            },"
echo "            \"url\": {"
echo "              \"raw\": \"http://localhost:8080/api/products\","
echo "              \"protocol\": \"http\","
echo "              \"host\": [\"localhost\"],"
echo "              \"port\": \"8080\","
echo "              \"path\": [\"api\", \"products\"]"
echo "            }"
echo "          }"
echo "        }"
echo "      ]"
echo "    }"
echo "  ]"
echo "}"
